const LIGHT = {
    MODE: "LIGHT",
    BACKGROUND_COLOR: "#FFFFFF",
    PRIMARY_COLOR: "#253A70",
    DARK_PRIMARY_COLOR: "#1B2A58",
    BUTTON_PRESS_COLOR: "#3B5591",
    ACTIVE_COMPONENT_COLOR: "#586D9F",
    TEXT_COLOR: "#000000",
    BUTTON_TEXT_COLOR: "#FFFFFF",
    LINE_COLOR: "#CCCCCC",
    INPUT_COLOR: "#E5E5E5",
    ERROR_COLOR: "#FF0000",
    ERROR_BACKGROUND_COLOR: "#FF4747",
}

const DARK = {
    MODE: "DARK",
    BACKGROUND_COLOR: "#000000",
    PRIMARY_COLOR: "#000000",
    BUTTON_PRESS_COLOR: "#3B5591",
    ACTIVE_COMPONENT_COLOR: "#586D9F",
    TEXT_COLOR: "#FFFFFF",
    BUTTON_TEXT_COLOR: "#FFFFFF",
    LINE_COLOR: "#FFFFFF",
    INPUT_COLOR: "#CCCCCC",
    ERROR_COLOR: "#FF0000",
    ERROR_BACKGROUND_COLOR: "#FF4747",
}

export { LIGHT, DARK }
